try{
    hello()
}
catch (error){
    console.log(error)
}

//

try {
    anotherFunction()
}
catch {
    console.log("esto es un error")
}